name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "MyDockerApp/**" # Chỉ chạy khi code Backend thay đổi
      - ".github/workflows/deploy-backend.yml" # Hoặc file workflow này thay đổi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Login vào Azure Container Registry
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 2. Build và Push Docker Image (BE)
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./MyDockerApp
          push: true
          # Dùng github.sha để tạo tag duy nhất cho mỗi lần commit
          tags: ${{ secrets.ACR_SERVER }}/backend:${{ github.sha }}

      # 3. Deploy lên Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "test-docker-be" # Thay tên App Service BE vào đây (VD: test-docker-be-...)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BE }}
          images: "${{ secrets.ACR_SERVER }}/backend:${{ github.sha }}"
